window.NEXARA = {
  nav: [
    { label: "Academy", trustLabel: "Talent Programmes", page: "academy" },
    { label: "Marketing", trustLabel: "Digital Solutions", page: "marketing" },
    { label: "Labs", trustLabel: "AI & Automation", page: "labs" },
    { label: "Proof", trustLabel: "Delivery Proof", page: "customers" },
    { label: "Contact", trustLabel: "Enquiry", page: "contact" },
  ],
  gateway: {
    neo: {
      kicker: "For teams that move before the market catches up.",
      title: "Loud, fast, fluorescent. The Nexara you'd screenshot for your story.",
      body: "Live cohorts, campaigns that hit, and AI systems that actually ship, from one team that treats every brief like launch week.",
      chips: ["no cap", "shipping daily", "vibes reserved"],
      cta: "Enter the Chaos",
    },
    trust: {
      kicker: "For institutions that need structured capability without the noise.",
      title: "Enterprise IT capability programmes.",
      body: "Nexara brings talent programmes, digital market systems and applied AI automation into one accountable operating model for enterprise teams.",
      chips: ["Talent operations", "Digital systems", "AI automation"],
      cta: "Enter the Firm",
    },
  },
  home: {
    neo: {
      eyebrow: "🚀 NEXARA GEN Z",
      title: "We build tomorrow's",
      accent: "internet_",
      body: "Academic programs, AI experiments, software shipping, and marketing that slaps. One studio, three obsessions. Pick your entrance — let's cook.",
      calloutTitle: "Three engines. Zero filler.",
      calloutBody: "Pick the track that hits your problem now. Then stack Academy, Digital Marketing and Labs together when the project needs people, presence, and systems all firing at once.",
    },
    trust: {
      eyebrow: "NEXARA ENTERPRISE",
      title: "Enterprise IT solutions across people, markets and automation.",
      accent: "Structured. Governed. Operational.",
      body: "Nexara helps organizations run talent enablement, digital market infrastructure and applied AI automation through three clearly defined solution lines.",
      calloutTitle: "One enterprise operating model across three solution lines.",
      calloutBody: "Trust keeps the same Nexara capabilities visible while translating them into corporate service lines, defined modules, delivery stages and review-ready reporting.",
    },
  },
  unbox: {
    neo: {
      eyebrow: "// UNBOX NEXARA",
      title: "Three engines. One operating core.",
      body: "Scroll through the gateway layer and see how Academy, Digital Marketing and Labs combine into one delivery model for growth-city teams.",
      sequence: "NEXARA CORE",
    },
    trust: {
      eyebrow: "Operating model",
      title: "One enterprise model across talent, digital and automation.",
      body: "The operating model keeps each solution line distinct while connecting project scoping, reporting, controls and production-readiness standards.",
      sequence: "Enterprise capability model",
    },
    faces: [
      { label: "Talent Programmes", sub: "Academy capability", section: "academy", color: "var(--unbox-academy)" },
      { label: "Digital Solutions", sub: "Market systems", section: "marketing", color: "var(--unbox-marketing)" },
      { label: "AI & Automation", sub: "Applied AI systems", section: "labs", color: "var(--unbox-labs)" },
      { label: "Scope", sub: "Scoped intake", section: "contact", color: "var(--unbox-briefs)" },
      { label: "Cities", sub: "Growth context", section: "home", color: "var(--unbox-cities)" },
      { label: "Standards", sub: "Delivery control", section: "company", color: "var(--unbox-standards)" },
    ],
    signals: [
      ["Talent", "cohorts, portfolios, placement readiness"],
      ["Digital", "positioning, websites, content, demand"],
      ["AI", "workflow discovery, AI systems, guardrails"],
      ["Core", "scoping, reporting, operating readiness"],
    ],
  },
  market: {
    title: {
      neo: "Built for growth cities that never sleep.",
      trust: "Designed for growing markets across India.",
    },
    body: {
      neo: "Nexara is tuned for places where talent is hungry, local brands are digitizing fast, and AI adoption is just getting real.",
      trust: "The operating focus is on Indian growth cities where education, local business growth and operational digitization are accelerating.",
    },
    cities: ["Visakhapatnam", "Vijayawada", "Coimbatore", "Indore", "Nagpur", "Surat", "Mysuru", "Bhubaneswar"],
    assumptions: [
      "Students and freshers need employable portfolios, English communication support and interview readiness.",
      "SMBs and regional brands need affordable brand, web, social and lead-generation systems.",
      "Hospitals, institutes, real estate, logistics and service businesses need practical automation before advanced AI.",
      "Buyers prefer clear packages, visible deliverables, local proof and WhatsApp-friendly enquiry flows.",
    ],
  },
  superSkills: [
    {
      title: "City Launch Stack",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Train the local crew, launch the brand, wire the follow-up — all before competitors finish their morning meeting.",
      trust: "A city-entry system combining talent enablement, market launch assets and practical automation.",
      stack: ["Hiring pipeline", "Launch website", "Lead capture", "AI follow-up"],
    },
    {
      title: "Placement Growth Loop",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Turn learner wins into proof, proof into demand, demand into better hiring loops. The flywheel is real.",
      trust: "Connects training outcomes, employer visibility and placement workflows into one operating loop.",
      stack: ["Cohort scoring", "Employer requirements", "Outcome stories", "Placement dashboard"],
    },
    {
      title: "AI-Ready Business Kit",
      sections: ["Digital Marketing", "Labs"],
      neo: "Give regional brands the website, data trail and automation layer they need before the AI wave lands. No more catching up.",
      trust: "Prepares growing businesses with clear web journeys, knowledge structure and first-stage automation.",
      stack: ["Service pages", "Knowledge base", "Document AI", "Workflow audit"],
    },
    {
      title: "Founder Visibility Engine",
      sections: ["Digital Marketing", "Labs"],
      neo: "Get the founder visible, sharpen the offer, make every inbound easy to chase. Stop hiding the best product in the room.",
      trust: "Supports founder-led companies with positioning, content cadence, enquiry capture and CRM-ready follow-up.",
      stack: ["Positioning", "Content system", "Landing pages", "Lead routing"],
    },
    {
      title: "Institution Outcome OS",
      sections: ["Academy", "Digital Marketing", "Labs"],
      neo: "Make colleges look outcome-first with training, reporting and placement proof that actually moves.",
      trust: "A structured operating layer for institutions that need cohort visibility, reporting and placement confidence.",
      stack: ["Training tracks", "Progress reports", "Demo days", "Placement analytics"],
    },
  ],
  sections: {
    academy: {
      id: "academy",
      index: "01",
      name: "Academy",
      short: { neo: "Learn fast. Build proof. Get placed. Receipts included.", trust: "Enterprise talent enablement and placement operations." },
      statement: "Talent isn't found — it's built. Cohort by cohort, project by project, until the portfolio speaks before the résumé does.",
      hero: {
        neo: {
          eyebrow: "🎓 NEXARA ACADEMY",
          title: "Skills that hit different.",
          accent: "Train. Build. Show.",
          body: "Live cohorts, real projects, mentor reviews and portfolio prep for learners who are done collecting certificates and ready to ship actual work.",
          primary: "See the tracks",
          secondary: "Placement proof",
        },
        trust: {
          eyebrow: "Talent Programmes",
          title: "Build enterprise-ready talent development operations.",
          accent: "From learning plan to hiring readiness.",
          body: "Nexara Academy supports students, institutions and employers with cohort-based training, portfolio assessment, internship workflows and placement-readiness operations.",
          primary: "Explore Talent Programmes",
          secondary: "View placement workflows",
        },
      },
      stats: [["6", "skill options"], ["3", "audience groups"], ["4", "delivery stages"], ["3", "programme packages"]],
      modules: [
        { title: "Career Tracks", neo: "Full-stack, AI, design and growth — sprint-based builds that turn learners into people worth hiring.", trust: "Role-aligned tracks across engineering, data, design, cloud and growth functions." },
        { title: "Internship Engine", neo: "Real projects, mentor pressure and weekly output. Move like a junior operator from week one.", trust: "Managed internship workflows with mentor reviews, delivery checkpoints and portfolio artifacts." },
        { title: "Placement Desk", neo: "Profile polish, mock interviews and partner matching — none of the generic placement-office theater.", trust: "Employer requirements, candidate screening, interview readiness and offer-stage tracking." },
        { title: "Campus Programmes", neo: "Turn classrooms into launch rooms. Dashboards students actually care about using.", trust: "Institution-ready skilling programmes with reporting, outcomes tracking and governance." },
      ],
      stack: ["Full-Stack Engineering", "Data & AI", "Product Design", "Cloud & DevOps", "Growth Marketing", "Portfolio Reviews"],
      audiences: [
        { title: "Students", neo: "For freshers who need an employable portfolio that stands out — not another PDF nobody reads.", trust: "For ambitious learners who need structured skill development, English-facing portfolio support and placement readiness." },
        { title: "Colleges", neo: "Give students a launch system that feels current. Make the placement cell proud.", trust: "For institutions that need internship structure, cohort dashboards and hiring-partner alignment." },
        { title: "Employers", neo: "Meet junior talent that has already shipped production code before the first call. No dry runs.", trust: "For regional IT firms, agencies and growing companies that need screened, project-tested entry-level candidates." },
      ],
      stackDetails: [
        { title: "Full-Stack Engineering", outcome: "Deployable apps", deliverables: ["React interfaces", "API foundations", "Database basics", "Deployment workflow"] },
        { title: "Data & AI", outcome: "Analytical projects", deliverables: ["Data cleaning", "Dashboards", "Model basics", "AI use cases"] },
        { title: "Product Design", outcome: "Portfolio-ready UX", deliverables: ["User flows", "Wireframes", "UI systems", "Case studies"] },
        { title: "Cloud & DevOps", outcome: "Operational fluency", deliverables: ["Git workflow", "Hosting", "CI basics", "Monitoring"] },
        { title: "Growth Marketing", outcome: "Campaign literacy", deliverables: ["Funnels", "Landing pages", "Content tests", "Reporting"] },
        { title: "Portfolio Reviews", outcome: "Hiring proof", deliverables: ["Project audits", "Resume review", "Mock interviews", "Profile polish"] },
      ],
      process: [
        { step: "01", title: "Map the learner", body: "Assess current skill level, target roles and portfolio gaps." },
        { step: "02", title: "Run the cohort", body: "Live sessions, project sprints, mentor reviews and weekly delivery." },
        { step: "03", title: "Build proof", body: "Turn projects into case studies, demos and interview-ready narratives." },
        { step: "04", title: "Place or partner", body: "Match candidates to interviews or report cohort outcomes." },
      ],
      packages: [
        { name: "Career Cohort", fit: "Students and freshers", price: "Priced per cohort and city", duration: "Set by track length", includes: ["Facilitated cohort sessions", "Project portfolio", "Mentor reviews", "Placement prep"] },
        { name: "Internship Batch", fit: "Colleges and academies", price: "Priced per batch size", duration: "Aligned to the academic calendar", includes: ["Managed internship", "Weekly reports", "Completion scoring", "Demo day"] },
        { name: "Hiring Pipeline", fit: "Employers", price: "Custom, role-based", duration: "Runs until roles close", includes: ["Role requirements", "Candidate screening", "Interview shortlist", "Offer tracking"] },
      ],
      faqs: [
        ["Is Academy only for students?", "No. Academy supports learner cohorts, college programmes and employer-led hiring pipelines, with scope adjusted for each audience."],
        ["Do you guarantee placement?", "Nexara provides placement preparation, portfolio support and hiring coordination where included in scope. Nexara does not publish a general placement guarantee; any hiring commitment must be separately scoped and documented."],
        ["How is the Academy programme structured compared to standard skilling courses?", "The programme is built around applied projects, mentor review, communication readiness and portfolio proof rather than passive course completion."],
      ],
      intake: { primary: "Plan an Academy programme", secondary: "Share city, learner count, target roles, timeline and placement expectations." },
      subpages: [
        {
          slug: "tracks",
          title: "Tracks",
          callout: { neo: "Pick a lane, build proof, stop sounding entry-level. The glow-up starts here.", trust: "Career tracks mapped to hiring signals and measurable skill outcomes." },
          cards: [
            { title: "Full-stack sprint", neo: "Ship interfaces, APIs and deployable flows. Real output, not slides.", trust: "Frontend, backend and deployment foundations in one applied track." },
            { title: "AI/data sprint", neo: "Go from notebooks to useful models and dashboards fast.", trust: "Data workflows, AI foundations and analytical project delivery." },
            { title: "Design studio", neo: "Build product taste, UX logic and portfolio screens worth showing.", trust: "UX, interface design and product presentation for hiring review." },
            { title: "Cloud operations", neo: "Learn the infra moves teams expect on day one. No excuses.", trust: "Cloud, DevOps and operational basics for junior technical roles." },
          ],
        },
        {
          slug: "internships",
          title: "Internships",
          callout: { neo: "Internships that feel like a real tech squad — not a certificate farm.", trust: "A managed bridge from learning into workplace delivery." },
          cards: [
            { title: "Mentor pods", neo: "Small groups, direct feedback, no hiding. This is peak learning.", trust: "Assigned mentors guide weekly progress and quality review." },
            { title: "Weekly reviews", neo: "Every week ends with a live demo, a score and next moves.", trust: "Regular checkpoints create accountability and measurable progress." },
            { title: "Client-style projects", neo: "Work on prompts that feel like actual business problems. Because they are.", trust: "Project scopes simulate professional delivery expectations." },
            { title: "Completion reports", neo: "Leave with proof that says what you can actually build.", trust: "Final reports document capability, participation and project quality." },
          ],
        },
        {
          slug: "placements",
          title: "Placements",
          callout: { neo: "Get good, get seen, get hired. That's the whole playbook.", trust: "Hiring-partner workflows built into the learning journey." },
          cards: [
            { title: "Interview prep", neo: "Practice until your answers stop sounding rehearsed.", trust: "Structured preparation for technical and behavioral interviews." },
            { title: "Partner matching", neo: "Match skills to teams that actually need them. No spray and pray.", trust: "Candidate profiles aligned with employer role requirements." },
            { title: "Offer tracking", neo: "Know where every application stands. No black holes.", trust: "Pipeline visibility from shortlist to interview to offer." },
            { title: "Alumni proof", neo: "Show the next cohort what the path looks like. Real receipts.", trust: "Outcome stories support institutional and employer confidence." },
          ],
        },
      ],
      proof: [
        { name: "Learner cohort", result: { neo: "Portfolio proof built for interviews, not a folder nobody opens", trust: "Applied projects converted into review-ready portfolios" }, org: "Academy programme" },
        { name: "College batch", result: { neo: "Internship rhythm made visible — weekly, scored, no guesswork", trust: "Weekly reporting and completion scoring introduced" }, org: "Institution programme" },
        { name: "Employer shortlist", result: { neo: "Screened profiles, less hiring theater", trust: "Role-fit screening and interview preparation delivered as part of the hiring pipeline" }, org: "Hiring support" },
      ],
    },
    marketing: {
      id: "marketing",
      index: "02",
      name: "Digital Marketing",
      short: { neo: "Make the brand impossible to ignore. Full stop.", trust: "Digital presence, web infrastructure and growth operations." },
      statement: "Attention is earned in the first ten seconds. Everything we build is engineered for that moment — and the decision that follows it.",
      hero: {
        neo: {
          eyebrow: "📣 NEXARA DIGITAL MARKETING",
          title: "We make the internet care.",
          accent: "get loud, stay loud.",
          body: "Positioning, websites, content systems and campaign loops built to convert. We put your offer in front of the people who actually matter — and keep it there.",
          primary: "See the growth stack",
          secondary: "Brand proof",
        },
        trust: {
          eyebrow: "Digital Solutions",
          title: "Build credible digital market infrastructure.",
          accent: "From positioning to demand systems.",
          body: "Nexara Digital Marketing supports brand identity, websites, content operations, SEO foundations and performance campaigns with clear deliverables and reporting.",
          primary: "Explore Digital Solutions",
          secondary: "View market outcomes",
        },
      },
      stats: [["6", "growth services"], ["4", "launch stages"], ["3", "channel layers"], ["3", "engagement packages"]],
      modules: [
        { title: "Brand Identity", neo: "Names, visuals and voice that don't look like a Canva template pack. Custom attitude only.", trust: "Naming, visual systems, messaging, launch kits and brand governance." },
        { title: "Web Experience", neo: "Pages that sell before users bounce. Your site should be your best closer.", trust: "Corporate websites, landing pages and product pages designed for conversion." },
        { title: "Social Studio", neo: "Content with taste, tempo and output that doesn't dry up. Stop the generic spam.", trust: "Always-on content systems for LinkedIn, Instagram, YouTube and community channels." },
        { title: "Performance Growth", neo: "Ads, SEO and reporting loops where the spend explains itself. Zero fluff.", trust: "Paid media, SEO, analytics dashboards and optimization cycles." },
      ],
      stack: ["Brand Systems", "Websites", "Social Media", "Performance Ads", "SEO", "Content Studio"],
      audiences: [
        { title: "Founders", neo: "For builders in growth cities who need people to get the offer in under ten seconds.", trust: "For founder-led companies that need positioning, site clarity and launch assets." },
        { title: "Growing Brands", neo: "For local leaders and service brands leaking attention across every channel. Fix the leaks.", trust: "For regional businesses that need consistent brand, content and acquisition execution." },
        { title: "Enterprise Teams", neo: "For multi-branch teams drowning in campaign chaos. One system, one rhythm.", trust: "For regional enterprise teams that need governance, reporting and repeatable campaign operations." },
      ],
      stackDetails: [
        { title: "Brand Systems", outcome: "Clear identity", deliverables: ["Positioning", "Visual system", "Messaging", "Launch kit"] },
        { title: "Websites", outcome: "Conversion-ready presence", deliverables: ["Site map", "UX sections", "Copy hierarchy", "Responsive build"] },
        { title: "Social Media", outcome: "Consistent visibility", deliverables: ["Content pillars", "Calendar", "Creative formats", "Publishing rhythm"] },
        { title: "Performance Ads", outcome: "Measured acquisition", deliverables: ["Campaign setup", "Creative tests", "Audience map", "Weekly reporting"] },
        { title: "SEO", outcome: "Search foundation", deliverables: ["Metadata", "Page structure", "Internal links", "Content plans"] },
        { title: "Content Studio", outcome: "Reusable assets", deliverables: ["Posts", "Carousels", "Short scripts", "Campaign copy"] },
      ],
      process: [
        { step: "01", title: "Position", body: "Clarify audience, category, offer and proof before design starts." },
        { step: "02", title: "Build assets", body: "Create brand, website, content and campaign assets as one system." },
        { step: "03", title: "Launch channels", body: "Publish the site, activate content and run performance campaigns." },
        { step: "04", title: "Optimize", body: "Review reporting, test creative, improve pages and compound winners." },
      ],
      packages: [
        { name: "Brand Launch", fit: "New or repositioning brands", price: "Priced per identity scope", duration: "Confirmed at kickoff", includes: ["Positioning", "Identity", "Messaging", "Launch assets"] },
        { name: "Website Growth", fit: "Companies with weak conversion", price: "Priced per site architecture", duration: "Set by page count and content readiness", includes: ["Site architecture", "Copy", "Design", "SEO foundations"] },
        { name: "Demand System", fit: "Teams ready to scale", price: "Monthly retainer, scoped to budget", duration: "Rolling, cadence agreed in scope", includes: ["Content calendar", "Paid campaigns", "Reporting", "Creative testing"] },
      ],
      faqs: [
        ["Do you only design websites?", "No. Website work can be delivered independently, but it is usually strongest when connected to positioning, content and lead-capture strategy."],
        ["Can Nexara run ongoing marketing?", "Yes. Nexara can support launch projects, monthly content operations and performance campaigns depending on scope and budget."],
        ["What do you need before starting?", "Nexara requires a defined offer, target audience, existing channel inventory, current website or creative assets, an approximate budget range, and a stated primary business objective before scoping begins."],
      ],
      intake: { primary: "Map a marketing system", secondary: "Share city, category, offer, current website, channels and primary growth goal." },
      subpages: [
        {
          slug: "brand",
          title: "Brand",
          callout: { neo: "Look sharp enough to get saved and shared. Custom details only, no template packs.", trust: "A complete identity system for consistent market presence." },
          cards: [
            { title: "Positioning", neo: "Say what you are before the market decides for you.", trust: "Clear category, audience and value proposition definition." },
            { title: "Visual identity", neo: "Logo, color, type — built with actual custom attitude, not vibes-as-a-service.", trust: "A usable visual system across digital and sales touchpoints." },
            { title: "Messaging", neo: "Copy that sounds like a company with a real pulse.", trust: "Messaging pillars for website, sales and campaign communication." },
            { title: "Launch kits", neo: "Everything needed to go live without the last-minute scramble.", trust: "Brand assets, templates and rollout guidance for launch teams." },
          ],
        },
        {
          slug: "web",
          title: "Web",
          callout: { neo: "Your website should be your best closer. Bounce rate is not a personality.", trust: "Web experiences designed to explain, convert and build confidence." },
          cards: [
            { title: "Landing pages", neo: "Fast, focused, one offer and one action. Nothing else.", trust: "Campaign pages with clear hierarchy, proof and conversion paths." },
            { title: "Corporate sites", neo: "A full website that feels alive — not an archived press kit.", trust: "Multi-section websites with service pages, proof and contact flows." },
            { title: "Product pages", neo: "Show the thing, explain the win, kill the doubt.", trust: "Product storytelling with features, outcomes and buyer reassurance." },
            { title: "SEO foundations", neo: "Make the site findable without making it boring.", trust: "Metadata, headings, internal links and structured content planning." },
          ],
        },
        {
          slug: "growth",
          title: "Growth",
          callout: { neo: "Campaigns that move actual numbers — not just deck slides.", trust: "Campaigns with clear measurement, reporting and optimization cadence." },
          cards: [
            { title: "Paid acquisition", neo: "Creative tests, budget discipline and hooks that earn the click.", trust: "Paid campaigns structured around audiences, offers and reporting." },
            { title: "Reporting", neo: "Dashboards people can read without a translator.", trust: "Weekly and monthly reports focused on pipeline and performance." },
            { title: "Retargeting", neo: "Bring back the warm audience before they forget you existed.", trust: "Retargeting journeys based on behavior, funnel stage and intent." },
            { title: "Creative testing", neo: "Ship variants fast, kill the losers, compound the winners.", trust: "Controlled testing of messages, formats and audience segments." },
          ],
        },
      ],
      proof: [
        { name: "Founder-led service brand", result: { neo: "Offer got sharper before the market got to judge it", trust: "Positioning, website architecture and enquiry flow defined and documented" }, org: "Brand and web" },
        { name: "Regional healthcare business", result: { neo: "Content stopped feeling random — pillars, pages, rhythm sorted", trust: "Content pillars, landing pages and reporting cadence defined" }, org: "Growth system" },
        { name: "Multi-location business", result: { neo: "Campaigns got a clean rhythm instead of spray-and-pray", trust: "Channel plan and performance review cadence established" }, org: "Campaign operations" },
      ],
    },
    labs: {
      id: "labs",
      index: "03",
      name: "Labs",
      short: { neo: "From prompt to product. We build agents that survive real traffic.", trust: "Applied AI systems, workflow automation and operational controls." },
      statement: "AI earns its place when it survives real traffic. We scope the workflow first, prove it second, and ship only what holds.",
      hero: {
        neo: {
          eyebrow: "🤖 NEXARA LABS",
          title: "From prompt to product.",
          accent: "Models, pipelines, the whole stack.",
          body: "Labs turns repetitive operations, messy documents and knowledge silos into AI-assisted systems with evaluation, guardrails and permissions baked in from day one.",
          primary: "See the lab stack",
          secondary: "Product proof",
        },
        trust: {
          eyebrow: "AI & Automation",
          title: "Deploy applied AI with enterprise control.",
          accent: "From workflow discovery to governed rollout.",
          body: "Nexara Labs designs and builds applied AI systems for document intelligence, knowledge retrieval, agent workflows and internal tools with practical controls from the start.",
          primary: "Explore AI & Automation",
          secondary: "View system patterns",
        },
      },
      stats: [["4", "AI build modules"], ["3", "deployment paths"], ["4", "control layers"], ["6", "stack capabilities"]],
      modules: [
        { title: "Atlas", neo: "Knowledge search with source trails, review paths and fewer loose threads.", trust: "A knowledge-retrieval pattern for documents, tickets, policies and wikis." },
        { title: "Pulse", neo: "Ask business questions in plain language. Stop waiting for dashboard bottlenecks.", trust: "A natural-language analytics pattern for product and business events." },
        { title: "Forge", neo: "Agent workflows with logs, traces and permissions locked in. Ship daily with brakes.", trust: "Agent workflow patterns with orchestration, controls, traces and evaluation." },
        { title: "Vault", neo: "Messy forms, contracts and invoices become clean structured data you can actually review.", trust: "Document intelligence patterns for invoices, forms, contracts and operational files." },
      ],
      stack: ["RAG", "Agents", "Document AI", "Evaluations", "Observability", "Private Deployment Scoping"],
      audiences: [
        { title: "Operations Teams", neo: "For teams drowning in manual forms, WhatsApp follow-ups, Excel sheets and the same question every Monday.", trust: "For teams that need to reduce manual work across documents, support and knowledge operations." },
        { title: "Product Teams", neo: "For software squads that need AI agents that actually survive real-world traffic — not just demos.", trust: "For product teams adding AI capability to existing software or internal platforms." },
        { title: "Leadership Teams", neo: "For owners who want AI tied to real workflows, not another presentation nobody acts on.", trust: "For decision-makers who need controlled pilots, governance and measurable adoption plans." },
      ],
      stackDetails: [
        { title: "RAG", outcome: "Grounded answers", deliverables: ["Source ingestion", "Retrieval design", "Answer grounding", "Feedback loop"] },
        { title: "Agents", outcome: "Controlled automation", deliverables: ["Tool access", "Workflow logic", "Guardrails", "Trace logs"] },
        { title: "Document AI", outcome: "Structured extraction", deliverables: ["Classification", "Field extraction", "Validation", "Export workflows"] },
        { title: "Evaluations", outcome: "Quality control", deliverables: ["Test sets", "Scoring", "Human review", "Regression checks"] },
        { title: "Observability", outcome: "Operational visibility", deliverables: ["Dashboards", "Latency checks", "Error tracking", "Usage monitoring"] },
        { title: "Private Deployment Scoping", outcome: "Controlled rollout plan", deliverables: ["Hosting review", "Access controls", "Audit needs", "Support handoff"] },
      ],
      process: [
        { step: "01", title: "Find the workflow", body: "Identify the repetitive or knowledge-heavy process where AI can create measurable value." },
        { step: "02", title: "Design the system", body: "Map data, models, integrations, permissions and evaluation criteria." },
        { step: "03", title: "Build and test", body: "Prototype, evaluate, review failures and harden the workflow." },
        { step: "04", title: "Deploy and observe", body: "Launch with monitoring, usage review and improvement cycles." },
      ],
      packages: [
        { name: "AI Discovery Sprint", fit: "Teams exploring AI use cases", price: "Fixed-scope sprint pricing", duration: "Short sprint, dates agreed in scope", includes: ["Workflow audit", "Feasibility map", "Risk review", "Pilot plan"] },
        { name: "Product Build", fit: "Teams ready to ship", price: "Priced per system architecture", duration: "Set by build phases", includes: ["Architecture", "Prototype", "Evaluation", "Production handoff"] },
        { name: "Automation Layer", fit: "Operations-heavy teams", price: "Retainer scoped to workflow count", duration: "Ongoing, support cadence agreed", includes: ["Agent workflows", "Integrations", "Monitoring", "Ongoing support cadence"] },
      ],
      faqs: [
        ["Do you build custom AI systems?", "Yes. Labs supports both reusable product patterns and custom builds around specific workflows, data sources and operational constraints."],
        ["How do you handle private data?", "Data handling, hosting, access control, audit logs and human review are scoped before build. Sensitive deployments can be designed around private or restricted environments where required."],
        ["What is the first step?", "Every Labs engagement begins with a workflow discovery session. Nexara maps the use case, defines pilot success criteria, identifies risk boundaries, and confirms a clear path to production or handoff before any build work begins."],
      ],
      intake: { primary: "Scope a Labs build", secondary: "Share city, workflow, data sources, current tools, risk level and success metric." },
      subpages: [
        {
          slug: "products",
          title: "Products",
          callout: { neo: "A lab shelf of robust patterns ready to scope, grounded before they ship.", trust: "Reusable product patterns designed around practical enterprise workflows." },
          cards: [
            { title: "Atlas", neo: "Grounded-answer search with source trails — every answer accountable.", trust: "Grounded-answer workflows for internal knowledge systems." },
            { title: "Pulse", neo: "Ask actual business questions without waiting on dashboard queues.", trust: "Natural-language analytics patterns over product and business events." },
            { title: "Forge", neo: "Agent workflows with brakes, logs and permissions locked in. Ship it right.", trust: "Controlled agent workflow patterns with tool access and evaluation." },
            { title: "Vault", neo: "Messy spreadsheets and operational docs turned into structured, reviewable data.", trust: "Extraction and classification patterns for operational documents." },
          ],
        },
        {
          slug: "ai-builds",
          title: "AI Builds",
          callout: { neo: "Custom AI with model selection, evaluations and RBAC sorted before you go live.", trust: "Custom AI systems scoped, evaluated and deployed with controls." },
          cards: [
            { title: "Discovery", neo: "Find the exact workflow where AI actually earns its keep.", trust: "Use-case mapping, feasibility review and success criteria." },
            { title: "Architecture", neo: "Pick the model, data path and guardrails before a single line gets written.", trust: "Solution architecture across data, models, tools and governance." },
            { title: "Build", neo: "Prototype fast, harden what survives, ship it.", trust: "Iterative development with testing, review and stakeholder demos." },
            { title: "Operate", neo: "Logs, evaluation monitoring and support loops running after launch.", trust: "Monitoring, evaluation, support and continuous improvement." },
          ],
        },
        {
          slug: "security",
          title: "Security",
          callout: { neo: "Move fast — with data boundaries locked down before the first build.", trust: "Private data, access controls and evaluation loops scoped before production." },
          cards: [
            { title: "Private hosting", neo: "Scope where sensitive systems and data should live before anything ships.", trust: "Deployment options can be reviewed against private hosting requirements." },
            { title: "RBAC", neo: "Not every user gets every lever. Permissions scoped in, not bolted on later.", trust: "Role-based access controls for users, tools and data." },
            { title: "Audit logs", neo: "Every important transaction leaves a trace. No black boxes.", trust: "Traceability for actions, retrieval, tool calls and outputs." },
            { title: "Human review", neo: "Humans stay in the loop where real judgment matters. Always.", trust: "Review workflows for risk-sensitive or high-impact outputs." },
          ],
        },
      ],
      proof: [
        { name: "Knowledge workflow", result: { neo: "Answers tied back to sources before they reach the workflow", trust: "Grounded knowledge assistant scoped for internal use" }, org: "Retrieval system" },
        { name: "Document workflow", result: { neo: "Manual fields became reviewable structured data", trust: "Extraction, validation and export workflow designed" }, org: "Document AI" },
        { name: "Operations workflow", result: { neo: "Repetitive follow-ups got a system instead of a sticky note", trust: "Controlled automation flow mapped with review checkpoints" }, org: "Agent workflow" },
      ],
    },
  },
  customers: [
    { id: "academy", section: "Academy", company: "Learner and college programmes", neo: "Training gets a visible rhythm: projects, reviews, portfolios and interview prep. No more mystery about what the cohort is actually producing.", trust: "Cohort structures can include applied projects, mentor checkpoints, reporting and placement-readiness support." },
    { id: "marketing", section: "Digital Marketing", company: "Founder and regional business launches", neo: "The offer gets sharper before the market judges it. One system for brand, web and demand.", trust: "Positioning, site architecture, content systems and reporting can be delivered as one market-readiness workflow." },
    { id: "labs", section: "Labs", company: "Operations and knowledge workflows", neo: "AI starts with the work that repeats every single week. Scope first, build second, ship with brakes.", trust: "Workflow discovery, retrieval systems, document AI and controlled automation can be scoped before production rollout." },
  ],
  company: {
    facts: [
      ["Status", "Incorporated company"],
      ["Sections", "Academy, Digital Marketing, Labs"],
      ["Focus", "Talent, market presence and applied AI systems"],
      ["Operating region", "India-first growth markets"],
    ],
    standards: [
      { title: "Verified claims", body: "Public numbers, client names and guarantees should only appear after approval and evidence." },
      { title: "Scoped delivery", body: "Every engagement starts with audience, goals, deliverables, timeline, ownership and success criteria." },
      { title: "Data boundaries", body: "Labs work scopes hosting, access, auditability, human review and risk before build." },
      { title: "Outcome reporting", body: "Academy, Marketing and Labs all need visible progress, completion and next-step reporting." },
    ],
    neo: {
      manifesto: "Nexara Gen Z is the IT company that doesn't act like one. Academy turns learning into portfolio proof, Digital Marketing turns offers into market signal, and Labs turns AI ideas into working systems — shipping daily across all three.",
      principles: [
        { title: "Keep the three engines loud", body: "Academy, Digital Marketing and Labs each keep their own edge while sharing one Nexara operating standard." },
        { title: "Build proof people can feel", body: "Show work, flows, scopes, outputs and review loops before making big outcome claims." },
        { title: "Move fast without going vague", body: "Momentum only counts when the offer, owner, timeline and next action are locked." },
        { title: "Ship production-grade or don't ship", body: "Every site, cohort, campaign and AI system should be built for real use — not presentation theater." },
        { title: "Never let the brand go generic", body: "Gen Z can sound sharp and the Firm can sound formal, but both should feel unmistakably Nexara." },
      ],
    },
    trust: {
      manifesto: "Nexara is an incorporated enterprise capability company with three focused solution lines: Talent Programmes for workforce readiness, Digital Solutions for market infrastructure, and AI & Automation for applied systems. Each line has its own delivery model while sharing standards for clarity, reporting, controls and production readiness.",
      principles: [
        { title: "Maintain distinct section ownership", body: "Academy, Digital Marketing and Labs remain separate service lines with clear scopes and decision paths." },
        { title: "Use shared standards and reporting", body: "Every engagement should define deliverables, cadence, evidence, handoff and next-step reporting." },
        { title: "Prioritize measurable outcomes", body: "Claims should connect to a scoped metric, review process or documented business objective." },
        { title: "Deliver production-quality systems", body: "Training operations, websites, campaigns and AI workflows should be usable beyond the first launch." },
        { title: "Give all three sections equal weight", body: "The gateway changes presentation mode without making one section feel secondary to another." },
      ],
    },
  },
  contact: {
    neo: {
      eyebrow: "LET'S BUILD",
      title: "We work with builders. Start here.",
      accent: "info@nexaragroups.com",
      body: "Pick a section. Tell us what you're building. We'll take it from there.",
      primary: "Get started",
    },
    trust: {
      eyebrow: "Project Enquiries",
      title: "Structured engagement starts with one conversation.",
      accent: "info@nexaragroups.com",
      body: "Define your section, city, audience and success metric. Nexara will map the appropriate next step.",
      primary: "Start an engagement",
    },
    channels: [
      { title: "Talent Programmes", section: "academy", body: "Learner count, target roles, city, duration, placement-readiness needs and reporting expectations." },
      { title: "Digital Solutions", section: "marketing", body: "Business category, offer, current website or channels, launch timeline and growth goal." },
      { title: "AI & Automation", section: "labs", body: "Workflow, data sources, current tools, access constraints, risk level and success metric." },
      { title: "Combined play", section: "home", body: "Use this when the project needs training, market presence and systems working together." },
    ],
    enquiry: {
      title: "Scope your project",
      body: "Fill out the planner. Once completed, your mail client will open a formatted message sent directly to our intake team.",
      label: "Send to info@nexaragroups.com",
      href: "mailto:info@nexaragroups.com",
    },
    checklist: ["Section and city", "Audience or user group", "Timeline and schedule", "Current assets or tools", "Success metric", "Decision-maker contact"],
  },
};
